### ISSUE TITLE
Logfile support

### ISSUE THREAD

**Issue by mseele** [jadolg/tor-snowflake-snap#1]
Thank you for that snap...this was the most easy way to install snowflake on my raspberry pi.
Maybe you can help me with one thing: Does the snowflake snap log into any logfile?
And if not, is it possible to extend the snap package or add logging capabilities in some way?

Thanks a lot for your support!

**Comment by jadolg** [comment]
Hi, right now the logs are only accessible if you query them from the snap service.
`snap logs tor-snowflake.snowflake -f`
This will catch logs written to stdout|stderr.

**Comment by mseele** [comment]
Thanks for the fast reply. Thats a good point to start, thank you.
But when I read the snowflake code correct, it will log nothing (or only errors) without giving the -log cli option. Please see https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/blob/main/client/snowflake.go#L174 and the following line.
Is it possible maybe to (optionally) give a cli option to the snap snowflake service?

**Comment by jadolg** [comment]
Will a fixed path solve the problem for you?
https://github.com/jadolg/tor-snowflake-snap/pull/2
This makes the log available in $SNAP_DATA so you can tail it with `tail -f /var/snap/tor-snowflake/current/snowflake.log`

**Comment by mseele** [comment]
Yeah, that sounds great

**Comment by jadolg** [comment]
Merged and released on the stable channel
